### PR TITLE
PureScript 0.11.x changes

### PR DESCRIPTION
**Pull request by themoritz**
Need to wait until https://github.com/zudov/purescript-strongcheck-generics/pull/7 is ready, and https://github.com/eskimor/purescript-argonaut-generic-codecs/pull/14 is released...

### CODE REVIEW

**Comment by legrostdg** [comment]
purescript-strongcheck-generics v1.0.0 is out!

**Comment by themoritz** [comment]
Pinging @eskimor :)

**Comment by eskimor** [comment]
sorry pretty busy :-)

**Comment by eskimor** [comment]
Thanks for pinging!

**Pull request merged**
